---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feaf-frontend-sa
  namespace: feaf-dashboard
  labels:
    app: feaf-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feaf-backend-sa
  namespace: feaf-dashboard
  labels:
    app: feaf-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feaf-postgres-sa
  namespace: feaf-dashboard
  labels:
    app: feaf-postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: feaf-dashboard
  labels:
    app: prometheus
